import type { Metadata } from "next";
import { Concert_One } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { HeroUIProvider, ToastProvider } from "@heroui/react";
import "./globals.css";


const concert = Concert_One({ subsets: ["latin"], weight: '400' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body
        className={`${concert.className}  antialiased `}
      >
        <SessionProvider>
          <HeroUIProvider>
            <ToastProvider placement="top-center" />
            {children}
          </HeroUIProvider>
        </SessionProvider>

      </body>
    </html>
  );
}
